### ISSUE TITLE
Error importing .qza files into R as a phyloseq object

### ISSUE THREAD

**Issue by ekquaye** [jbisanz/qiime2R#33]
Hi JBisanz,

I tried importing .qza files (feature table, metadata file, taxonomy file, and a tree file) as a phyloseq object using the qiime2R package (version ‘0.99.6’), but I keep getting an error in the form
"Error in FUN(X[[i]], ...) : 
  numbers of left and right parentheses in Newick string not equal".

However,
1. I am able to create the phyloseq object without the tree file using qiime2R (version ‘0.99.6’)
2.  Also, I am able to create the phyloseq object (**including the tree.qza file**) using an older version of qiime2R ('0.99.34') on a less powerful PC of mine.

Could you please help me overcome this error?

**Comment by jbisanz** [comment]
Interesting, this wouldn't be coming from qiime2R per se, but rather from the `read.tree` function of the package ape. It looks like this ?bug? was fixed in ape so I would think installing the latest version should fix your issue.

**Comment by ekquaye** [comment]
Thank you for the response, jbisanz.
I use the latest version of ape (version 5.5), but, unfortunately, the error still persists.

**Comment by neal-caffry19** [comment]
@ekquaye 
Hi ekquaye,

    Have you solved your problem yet? I met the same problem as you, can you tell me how you solved it?
